nikita_bukreev:_homework_10_completed
eugene-okulik/congenial-testers pull request #110
Opened 2023-11-15 19:44 UTC by NikitaBukreev

оставил комменты с просьбой помочь в коде)

2023-11-15 19:57 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_10/task_1.py
> +    def wrapper(first, second, operation):
вот тут пайчарм вообще ругается на operation в параметрах, но если его убрать, то тоже ругается(
а если сделать *args, то вообще весь код красным подчеркивать начинает(

2023-11-20 09:15 UTC, eugene-okulik requested changes

2023-11-20 09:15 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_10/task_1.py
> +    def wrapper(first, second, operation):   # operation вообще не подсвечивается (тип не используется)
Пайчарм тебе подсказывал, но ты не докрутил. Можно было не ждать операцию, которой ты действительно не пользуешься
```python
def wrapper(first, second):
```

2023-11-20 09:15 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_10/task_1.py
> +print(calc(-12, 11, '+-*/'))
И если во `wrapper` не ждать лишнего, то и здесль лишнее не нужно было бы передавать
```python
print(calc(10, 10))
print(calc(12, 11))
print(calc(12, 13))
print(calc(-12, 11))
```

2023-11-20 09:15 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_10/task_1.py
> +# Буду благодарен за подсказки, т.к. очень кривенько вышло=)
Не особо-то и кривенько. Так, в паре мест причесать.

2023-11-20 09:15 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_10/task_2.py
> +my_price = dict([x for x in separate_price(PRICE_LIST)])
Если остальное оставить как есть, то эта строка могла быть такой
```python
my_price = dict(separate_price(PRICE_LIST))
```
И тогда условия задания не выполнены )))

2023-11-20 09:15 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_10/task_2.py
> +        yield new_line[0], int(new_line[1])
А вот этот цикл можно было написать однострочным генератором.  
Ну, и, если это сделать, возможно, станет выидно, что можно вообще всё одной строкой сделать.

2023-12-20 19:34 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_10/task_1.py
> +    def wrapper(first, second, operation):   # operation вообще не подсвечивается (тип не используется)
поправил

2023-12-20 19:34 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_10/task_1.py
> +print(calc(-12, 11, '+-*/'))
поправил) изначально думал, что мы же делаем надстройку над калькулятором, вот и нужно передавать три аргумента=)

2023-12-20 19:36 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_10/task_2.py
> +my_price = dict([x for x in separate_price(PRICE_LIST)])
посмотрел у других, посмотрел свое, подумал и поправил в одну строку) но мне подобные решения никогда не нравились, не понимаю я этих стараний написать все в одну строку%)

2023-12-20 19:37 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_10/task_2.py
> +        yield new_line[0], int(new_line[1])
оставил серым свой переделанный цикл и запили все в одну строку)

2023-12-20 19:39 UTC, NikitaBukreev reviewed
вроди все поправил)

2023-12-21 08:15 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_10/task_2.py
> +my_price = dict([x for x in separate_price(PRICE_LIST)])
десь мы это делаем для практики. В живой природе я тоже не поддерживаю стараний написать всё в одну строку. Это в итоге получается нечитаемо.

2023-12-21 08:15 UTC, eugene-okulik approved these changes

2023-12-21 08:16 UTC, merged