nikita_bukreev_homework_16_completed
eugene-okulik/congenial-testers pull request #173
Opened 2024-01-05 10:57 UTC by NikitaBukreev

2024-01-08 08:03 UTC, eugene-okulik requested changes

2024-01-08 08:03 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_16/sql.py
> +last_user_id = [item['id'] for item in db_query(query0)][0]
Ну и здесь ты выполняешь запрос с LIMIT 1, значит ты уверен, что вернется один результат, который можно обработать с помощью `fetch_one`, и тогда не пришлось бы брать значение по индексу. Но твоя функция к этому не готова )))

2024-01-08 08:03 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_16/sql.py
> +('Весь нобрь1', (select id from subjets where title = 'QA1')),
А если этот код запустить несколько раз, то `id` какого предмета будет получено?

2024-01-09 08:42 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_16/sql.py
> +db_query(query1)
починил)

2024-01-09 08:43 UTC, NikitaBukreev commented on homework/nikita_bukreev/Homework_16/sql.py
> +('Весь нобрь1', (select id from subjets where title = 'QA1')),
вроди тоже поправил

2024-01-15 09:07 UTC, eugene-okulik approved these changes
Всё же лучше не пользоваться питоновскими подстановками, а делать всё неуязвимым для инъекций.

2024-01-15 09:07 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_16/sql.py
> +query1 = "INSERT INTO students (name, second_name, group_id) values ('Nikita2', 'Bukreev2', 1)"
Можно было ('Nikita2', 'Bukreev2', NULL)

2024-01-15 09:07 UTC, eugene-okulik commented on homework/nikita_bukreev/Homework_16/sql.py
> +where id = {student_id}'''
Эмм.
```
update students set group_id = {group_id} where id = {student_id}
```

2024-01-15 09:08 UTC, merged