Evgenii Timofeev: Homework 18 is completed
eugene-okulik/congenial-testers pull request #175
Opened 2024-01-07 12:37 UTC by Voyager17

2024-01-08 08:41 UTC, eugene-okulik requested changes
Смотрю в основном на оформление кода и на соответствие требованиям. Заковыристых багов не пытаюсь найти.  

По коду - очень аккуратный код, который легко читать. Большая редкость для обучающихся (даже для тех, кто не с нуля).  
По требованиям - ну там я тебе обозначил, что для аутпута дефолт у тебя неправильный - фиксится за полсекунды ))). Но еще из требований у тебя не реализовано вот это:

> Поиск по отсутствию текста в сообщении (отсеивание ненужных)

Если не совсем понятно о чем это. То объясню на примере. Допустим я ищу все сообщения со словом polygon, но вижу, что в результатах у меня слишком много лишнего для меня и тогда я в поиск добавляю то, что из результата нужно выкинуть, например слово warning (там нет такого, но я например). И тогда я получаю все сообщения, где есть слово polygon и нет слова warning.  

Помечаю как changes requested из-за отсутствующего функционала. Так бы принял )))

2024-01-08 08:41 UTC, eugene-okulik commented on homework/evgenii_timofeev/homework_20_python/script.py
> +- -t, --date: Фильтрация сообщений по определенной дате (формат YYYY-MM-DD).
YYYY-MM-DD у всех сообщений в логе чуть ли не одинаковые. Некоторые из них различаются милисекундами. Поэтому, стоило бы опираться на тот формат даты, который есть в логах (2022-02-03 09:07:31.159)

2024-01-08 08:41 UTC, eugene-okulik commented on homework/evgenii_timofeev/homework_20_python/script.py
> +        default="full",
> Так как каждое сообщение очень длинное, по умолчанию выводить первые 300 символов сообщения

2024-01-08 10:21 UTC, Voyager17 commented on homework/evgenii_timofeev/homework_20_python/script.py
> +- -t, --date: Фильтрация сообщений по определенной дате (формат YYYY-MM-DD).
Fixed

2024-01-08 10:21 UTC, Voyager17 commented on homework/evgenii_timofeev/homework_20_python/script.py
> +        default="full",
fixed

2024-01-15 09:11 UTC, eugene-okulik approved these changes

2024-01-15 09:11 UTC, merged