Sergey: Homework_22 comleted
eugene-okulik/congenial-testers pull request #206
Opened 2024-01-29 15:22 UTC by SergeyBurak

2024-01-30 07:37 UTC, eugene-okulik requested changes
Нет теста на создание объекта  
При изменении объекта нет проверки того, что объект изменился, ведь он уже мог иметь то содержание, на которое произошло изменение. А в test_put ты проверяешь то значение, которое не менял.  
Сообщение "Start testing" может появиться не в начале тестирования, если мы добавим тест, которому не нужна эта фикстура.  
Если какой-то предыдущий тест найдет багу и этой багой сломает объект, то следующие тесты не смогут отработать.

2024-02-01 08:49 UTC, eugene-okulik requested changes
И вот эта проблема всё еще есть

> Если какой-то предыдущий тест найдет багу и этой багой сломает объект, то следующие тесты не смогут отработать.

2024-02-01 08:49 UTC, eugene-okulik commented on homework/sergey_burak/Homework_22/test_RestAPI_pytest.py
> +    assert response['name'] == "SamSung MacBook Pro 16", 'Incorrect name, or object not created'
У тебя для всех тестов используется один и тот же объект. Не факт, что этот тест отработает первым. Возможно, объект уже будет изменён. Тогда тест упадёт, хотя баги то и нет.

2024-02-01 08:49 UTC, eugene-okulik commented on homework/sergey_burak/Homework_22/test_RestAPI_pytest.py
> +    assert response['name'] == "SamSung MacBook Pro 16", 'Incorrect name, or object not created'
И создание объекта в этом тесте - это не предусловие. Это и есть шаг теста.

2024-02-01 08:49 UTC, eugene-okulik commented on homework/sergey_burak/Homework_22/test_RestAPI_pytest.py
> +    assert response['data']['price'] == 12849.99, 'Price so mach!'
Ты всё еще проверяешь то значение, которое не менял.

2024-02-01 13:57 UTC, SergeyBurak commented on homework/sergey_burak/Homework_22/test_RestAPI_pytest.py
> +    assert response['data']['price'] == 12849.99, 'Price so mach!'
Но почему? Цена была 2849.99 стала 12849.99 Может это не совсем заметно, ок

2024-02-02 15:08 UTC, eugene-okulik commented on homework/sergey_burak/Homework_22/test_RestAPI_pytest.py
> +    assert response['data']['price'] == 12849.99, 'Price so mach!'
ааа, точняк.

2024-02-02 15:11 UTC, eugene-okulik approved these changes

2024-02-02 15:11 UTC, eugene-okulik commented on homework/sergey_burak/Homework_22/test_RestAPI_pytest.py
> +    assert response['name'] == "SamSung MacBook Pro 16", 'Incorrect name, or object not created'
Всё, отстал я от тебя )))  
Но правильнее в этом тесте делать непосредственно пост запрос по созданию объекта, а не пользоваться предусловием.  
Когда будешь превращать эти тесты в проект, учти это.

2024-02-02 15:11 UTC, merged