done_with_homework_4
eugene-okulik/congenial-testers pull request #34
Opened 2023-10-24 19:46 UTC by fixplays

please approve

2023-10-26 05:49 UTC, eugene-okulik requested changes
Нужно подправить работу с тем, что под ключом `dict`. Остальное - рекомендации.

2023-10-26 05:49 UTC, eugene-okulik commented on homework/dmitry_omelchenko/homework_4_python_basic_2/homework_4.py
> +    print(key, ":", value)
можно было просто распечатать словарь
```python
print(my_dict[my_dict_key])
```

2023-10-26 05:49 UTC, eugene-okulik commented on homework/dmitry_omelchenko/homework_4_python_basic_2/homework_4.py
> +my_dict_value = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, ('i am a tuple',): 6}
Если изначальный словарь изменится, то твой код будет неправильным
Допустим, станет так:
```python
my_dict = {
    'tuple': (1, 2, 3, 4, 5),
    'list': [10, 20, 30, 40, 50],
    'dict': {'x': 4, 'y': 5, 'z': 8, 'w': 11, 'v': 15},
    'set': {100, 200, 300, 400, 500}
}
```
Как сделать так, чтобы твой код смог справиться и с таким?

2023-10-26 05:49 UTC, eugene-okulik commented on homework/dmitry_omelchenko/homework_4_python_basic_2/homework_4.py
> +    print(key, ':', value)
Ну и здесь достаточно бы было простого распечатывания `my_dict`

2023-11-12 22:25 UTC, fixplays commented on homework/dmitry_omelchenko/homework_4_python_basic_2/homework_4.py
> +my_dict_value = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, ('i am a tuple',): 6}
fixed

2023-11-12 22:55 UTC, fixplays commented
Please verify

2023-11-16 14:18 UTC, eugene-okulik requested changes
Нужно избавиться от ручного копирования данных во время работы с ними. Ведь данные уже все внесены в переменную my_dict, потом мы только изменяем их. Но значение никакого из ключей не должно быть изменено целиком.

2023-11-16 14:18 UTC, eugene-okulik commented on homework/dmitry_omelchenko/homework_4_python_basic_2/homework_4.py
> +my_dict_value = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
Здесь ты пересоздаешь значения словаря. В словаре my_dict уже есть значение для ключа 'dict'. Если ты хочешь внести его в переменную my_dict_value, то можно сделать так:
```python
my_dict_value = my_dict['dict']
```
А твоему коду абсолютно все равно что там хранится в словаре my_dict под ключом 'dict'. Что бы там ни было, добавление и удаление элементов произойдет только с вот этим `{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}`

2023-11-16 14:19 UTC, eugene-okulik commented
Если не совсем понятно, пиши мне в телеграм

2023-11-21 10:22 UTC, fixplays commented
Полностью все пересмотрел и изменил, как мне кажется в лучшую сторону

2023-12-01 14:18 UTC, eugene-okulik commented
Закрываю этот пулл реквест, так как задание выполнено в другом пулл реквесте

2023-12-01 14:18 UTC, closed without merging