alina_hw_4
eugene-okulik/congenial-testers pull request #46
Opened 2023-10-27 11:40 UTC by kravAlin

updated_alina_hw_4

2023-11-02 07:37 UTC, eugene-okulik requested changes

2023-11-02 07:37 UTC, eugene-okulik commented on homework/AlinaKravch/alina_homework_4/lina_homework_4.py
> +dictionary['dict'][('i am a tuple',)] = 'Alex'
Этой строчкой в весь словарь dictionary ты добавила новый ключ `dict`, а внутрь него попыталась добавить ключ [('i am a tuple',)], но этот код не отработает, так как элемент под ключом `dict` не знает о том, что он словарь.
Так как элемент словаря в своем dictionary ты назвала `my_dict`, то и ключ [('i am a tuple',)] нужно было добавить в то, что у тебя под ключом `my_dict`

2023-11-02 08:55 UTC, kravAlin commented on homework/AlinaKravch/alina_homework_4/lina_homework_4.py
> +dictionary['dict'][('i am a tuple',)] = 'Alex'
Ок, если правильно поняла, то исправила на ['my_dict']

2023-11-04 17:35 UTC, eugene-okulik approved these changes

2023-11-04 17:35 UTC, merged