Dmitriy Popov: Homework_5 done
eugene-okulik/congenial-testers pull request #56
Opened 2023-10-29 20:57 UTC by d1amosha

2023-10-31 08:18 UTC, eugene-okulik requested changes
Всё хорошо, осталось порешать со срезами и индексом

2023-10-31 08:18 UTC, eugene-okulik commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +number_1 = int(result_1[-2:])
В условиях я не указал, что количество цифр в результате может быть разным, но я там указал, что решить нужно с помощью срезов и `index`  
Здесь срез есть, а `index` нет.

2023-10-31 08:18 UTC, eugene-okulik commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +# Task 3 Variant 2
Вариант 2 рулит

2023-11-01 16:31 UTC, d1amosha commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +number_1 = int(result_1[-2:])
Переделал, запушил новую версию )

2023-11-01 16:32 UTC, d1amosha commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +# Task 3 Variant 2
оставил только второй вариант )

2023-11-02 07:43 UTC, eugene-okulik requested changes

2023-11-02 07:43 UTC, eugene-okulik commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +res_2_index = res_2.index(res_2[20:])
А что такое 20? Откуда оно берется?  
Предположим, та программа начала выводить результат так: "результат работы программы: 42"  
Например, я другой девелопер и мне нужно в твою программу внести изменения. Как мне понять что нужно исправить, чтобы все снова работало хорошо?  
Как сделать так, чтобы в твою программу и не нужно было вносить изменения, если текст поменяется так, как я написал?

2023-11-02 07:45 UTC, eugene-okulik commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +res_2_index = res_2.index(res_2[20:])
Это 20 - это классическое "магическое число" (https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)) - часть "Плохая практика программирования"

2023-11-02 15:48 UTC, d1amosha commented on homework/dmitriy_popov/Homework_5/Homework_5.py
> +res_2_index = res_2.index(res_2[20:])
Исправил, чтоб работало даже если текст перед числом станет длиннее

2023-11-06 14:24 UTC, eugene-okulik approved these changes

2023-11-06 14:24 UTC, merged