Sergey: Homework 4 completed
eugene-okulik/congenial-testers pull request #60
Opened 2023-10-30 16:09 UTC by SergeyBurak

2023-10-30 17:10 UTC, SergeyBurak commented on homework/sergey_burak/Homework_4/Dictionary.py
> +my_dict['dict']['''('i am a tuple',)'''] = 'Holyday'
Вот, сразу что пришло в голову, не знаю правильно иль нет: т.к. В словаре этот ключ в двойных кавычках, почему-то?

2023-10-31 08:33 UTC, eugene-okulik requested changes
Кроме этого i am a tuple все ок

2023-10-31 08:33 UTC, eugene-okulik commented on homework/sergey_burak/Homework_4/Dictionary.py
> +my_dict['dict']['''('i am a tuple',)'''] = 'Holyday'
Сейчас у тебя выполнено задание

> добавьте элемент с ключом "('i am a tuple',)" и любым значением

а нужно

> добавьте элемент с ключом ('i am a tuple',) и любым значением

Более по-русски: ключом должен быть кортеж с одним элементом. Элемент, который должен быть в кортеже - строка с текстом i am a tuple

2023-11-06 14:23 UTC, eugene-okulik approved these changes

2023-11-06 14:23 UTC, merged