Makismb less5
eugene-okulik/congenial-testers pull request #88
Opened 2023-11-07 20:34 UTC by ju8er

2023-11-09 10:19 UTC, eugene-okulik requested changes
Задание №2 выполнено хорошо. Жду еще первого и третьего

2023-11-10 18:39 UTC, ju8er commented
в одном файле все 3 задания
по условиям задания не надо было создавать несколько новых файлов

2023-11-16 14:26 UTC, eugene-okulik commented
> в одном файле все 3 задания по условиям задания не надо было создавать несколько новых файлов

Видимо, мне гитхаб так отобразил. Пару раз я уже видел, что почему-то ображается не все содержимое и надо что-то там нажать, чтобы всё отобразилось.

2023-11-16 14:26 UTC, eugene-okulik approved these changes

2023-11-16 14:26 UTC, merged